// Generated by `npx expo lint` (https://docs.expo.dev/guides/using-eslint/), then narrowed.
//
// Same philosophy as frontend/eslint.config.js and admin-portal/eslint.config.js, which state it
// explicitly: this is a diagnostic for bug classes, not a style ruleset. eslint-config-expo is a
// broad preset, so the rules turned off below are the ones that flag correct code -- each with the
// reason, so the next person can tell "we decided this" from "nobody looked".
//
// Everything not mentioned here stays at Expo's defaults, including the rules that do catch real
// bugs (react-hooks/rules-of-hooks, no-unused-vars, and the import resolution checks) -- turning
// no-unused-vars on is what found the dead ActivityIndicator import in ImportScreen.tsx.
const { defineConfig } = require('eslint/config');
const expoConfig = require('eslint-config-expo/flat');

module.exports = defineConfig([
  expoConfig,
  {
    ignores: ['dist/*', '.expo/*', 'node_modules/*'],
  },
  {
    rules: {
      // Flags apostrophes in JSX text -- "You'll review every transaction" wants &apos;. The rule
      // exists for `>` and `}`, which really are ambiguous in JSX; an apostrophe is not, and
      // escaping it makes the source harder to read and to translate later for no rendering
      // difference at all. Off, rather than escaping five strings to satisfy it.
      'react/no-unescaped-entities': 'off',

      // Warns that `axios.create` / `axios.isAxiosError` could be written as named imports. They
      // could, and the default-import form used here is equally correct and matches the web app's
      // client.ts. This rule only fires on axios and only reports that two spellings exist.
      'import/no-named-as-default-member': 'off',
    },
  },
  {
    // Test files legitimately do things production code must not.
    files: ['**/*.test.ts', '**/*.test.tsx', 'src/test/**'],
    rules: {
      // Jest module-registry work (jest.resetModules() then re-require for a fresh module, or
      // reading a mock after jest.mock has replaced it) cannot use a static import: imports are
      // hoisted above the very calls that make the require correct.
      '@typescript-eslint/no-require-imports': 'off',

      // The standard React Testing Library pattern for asserting on a hook's value is a component
      // that assigns it to a variable in the enclosing scope. The rule is right that this is a
      // side effect during render -- that is exactly the point, and it is confined to a test
      // harness that renders once.
      'react-hooks/globals': 'off',
    },
  },
]);
