/**
 * Turns a missing build artefact into a real 404, which Cloudflare Pages will not do on its own.
 *
 * <h2>A deliberate copy of the user app's</h2>
 *
 * Identical to `frontend/functions/assets/[[path]].ts`, and duplicated rather than shared because
 * the admin portal is a SEPARATE Cloudflare Pages project with its own root directory and its own
 * build -- a Function has to live under the project Cloudflare deploys, so there is no location
 * from which one file could serve both. This matches how the two apps already treat `ErrorBoundary`
 * and `monitoring`. If a third app appears, that is the point to reach for a shared package rather
 * than a third copy.
 *
 * The admin portal is smaller and its users are operators rather than customers, which is the
 * argument for skipping it -- but its exposure is the same, and its assets were worse off: they
 * were served `max-age=0, must-revalidate`, so every one revalidated on every load.
 *
 * <h2>What this fixes</h2>
 *
 * Pages answers any unmatched path with the SPA fallback: `index.html`, `200`, `text/html`. That is
 * correct for routes -- `/login` is not a file, the client router owns it -- and wrong for assets.
 * A chunk deleted by a deploy came back as HTML with a success status, so a browser expecting
 * JavaScript reported a MIME mismatch instead of "this file is gone", and every layer downstream
 * had to infer the real cause from the wrong error. See
 * `docs/engineering/incidents/2026-08-08-stale-chunk-login-failure.md`.
 *
 * <h2>Why a Function, when `_redirects` looks like it should do this</h2>
 *
 * It cannot, and both dead ends are recorded because they look plausible and cost a deploy each to
 * disprove:
 *
 *  - `_redirects` needs a destination, so a 404 rule needs a `404.html` -- and adding that file
 *    REPLACES the SPA fallback, because Pages prefers `404.html` over `index.html` for unmatched
 *    paths. Every client route 404s. Measured on a preview: `/login`, `/about`, `/terms`,
 *    `/dashboard` all gone.
 *  - Repairing that with `/* /index.html 200` does not work either: Pages does not honour a `200`
 *    rewrite in `_redirects`.
 *
 * A Function is the only mechanism that can distinguish "no such asset" from "a route" without
 * disturbing the fallback that routes depend on.
 *
 * <h2>Scope, and why it is safe</h2>
 *
 * `[[path]]` is a catch-all mounted at `/assets/` ONLY. Everything Vite emits there is a
 * content-hashed build artefact whose URL was generated by the build itself, so a request that
 * matches nothing always means "this file no longer exists" and never "this is a route". Nothing
 * outside `/assets/` reaches this handler, so client-side routing is untouched by construction --
 * which is precisely the property the `_redirects` attempts could not offer.
 *
 * <h2>Cost</h2>
 *
 * This adds a Worker invocation to asset requests that miss the browser and edge caches. Acceptable
 * here because `public/_headers` marks these responses `immutable, max-age=31536000`: a given
 * hashed URL is fetched once per client and then never revalidated, so the steady-state invocation
 * count is roughly "new assets x new visitors", not "every page view".
 */

/**
 * The one piece of the Pages Functions context this handler touches, declared locally rather than
 * depending on `@cloudflare/workers-types`.
 *
 * A whole types package to name a single zero-argument method is a poor trade, and it would be a
 * production dependency of the deployed Worker bundle for the sake of one annotation. `Request` and
 * `Response` come from the DOM lib the app already compiles against and are structurally identical
 * to the Workers runtime's.
 */
interface AssetRequestContext {
  /** Runs the rest of the Pages pipeline: the next Function if there is one, otherwise the static
   *  asset lookup -- including the SPA fallback when nothing matches. */
  next: () => Promise<Response>;
}

/**
 * True when a response under `/assets/` is the SPA fallback rather than a real file.
 *
 * The test is the content type, not the status, because the status is exactly what is wrong: the
 * fallback is a `200`. Under `/assets/` an HTML body can only be the fallback, since Vite emits
 * scripts, stylesheets, fonts and images there and never a document.
 *
 * Exported so the decision is unit-testable without a Workers runtime. This file is deployed
 * straight to the edge and is not covered by the app's build, so the test is the only thing
 * standing between a mistake here and every asset request in production.
 */
export function isSpaFallback(response: Response): boolean {
  // A 304 carries no content type and must pass through untouched -- it means the client already
  // holds the file, which is the opposite of the file being missing. `ok` is false for 304, so
  // this returns early rather than mistaking an absent header for HTML.
  if (!response.ok) return false;

  const contentType = response.headers.get('content-type') ?? '';
  return contentType.toLowerCase().includes('text/html');
}

export async function onRequest(context: AssetRequestContext): Promise<Response> {
  const response = await context.next();

  if (!isSpaFallback(response)) return response;

  // Deliberately `no-store`. A content-hashed name is never reused, so a 404 here is permanent in
  // principle -- but "permanent" assumes the deploy that should have published the file is
  // finished, and caching a miss recorded mid-propagation would outlive the condition that caused
  // it. The failure this exists to report is already rare and already self-heals on the client;
  // making it sticky at the edge would be the worse trade.
  return new Response('Not found\n', {
    status: 404,
    headers: {
      'content-type': 'text/plain; charset=utf-8',
      'cache-control': 'no-store',
    },
  });
}
