package com.finora.imports.pdf;

import com.finora.imports.pdf.fixtures.PdfTraceRedactor;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Locale;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * PdfTextExtractor's raw output for a fixed PDF, frozen as a committed text file.
 *
 * <h2>Why this is not covered by GoldenOutputSnapshotTest</h2>
 * That test freezes the pipeline's output for the three committed traces, and it is deliberately
 * blind to this. A trace IS the output of PdfTextExtractor -- it is replayed from PdfTableLocator
 * down, which is exactly what makes it independent of PDFBox and of the original file (see
 * TraceFixtureRegressionTest's own doc comment). Every trace-driven test therefore starts AFTER
 * extraction has already happened, with coordinates recorded under whichever PDFBox version
 * captured them.
 *
 * The consequence: before this test, a PDFBox upgrade could shift a column position, a glyph
 * width, or a run boundary and the entire suite would still pass. That is not a hypothetical
 * failure mode. Upgrading 3.0.3 -> 3.0.8 pulled in three changes that land on this exact code
 * path -- removeContainedSpaces (PDFBOX-5487) drops space glyphs contained within an adjacent
 * letter and runs ONLY in the sortByPosition branch, which PdfTextExtractor enables; /ActualText
 * marked content rewrites a TextPosition's unicode; and font-change detection moved from instance
 * identity to font name, feeding the heuristic that decides where one writeString run ends and
 * the next begins. Output turned out to be byte-identical, but nothing in this repository could
 * have told us that.
 *
 * <h2>Why this fixture</h2>
 * separate_debit_credit_balance_sample.pdf is the only PDF whose BYTES are fixed in the
 * repository. Every PdfFixtureBuilder sample is generated by PDFBox at test time, so a snapshot
 * of one would conflate a change in PDF generation with a change in extraction and fail for
 * whichever moved. Pinning the fixed-byte document is what isolates the extractor.
 *
 * <h2>Why the snapshot is redacted</h2>
 * The runs are passed through {@link PdfTraceRedactor} before being written, exactly as a captured
 * trace is. The fixture is synthetic, so this is not protecting anyone -- it keeps the committed
 * artifact consistent with every other extraction artifact in this repository, and it means the
 * file cannot become a route for real statement data if the fixture is ever replaced by a captured
 * one. Redaction masks letters and digits but preserves run boundaries, lengths and every
 * coordinate, which is precisely what an extraction change would move: a dropped space, a split
 * run or a shifted column all still show up. A changed digit would not, and cannot happen without
 * the PDF's own bytes changing, which git already guards.
 *
 * <h2>Reading a failure</h2>
 * Like GoldenOutputSnapshotTest, a mismatch is a question rather than a verdict: the same bytes
 * now extract differently. If that is an intended library upgrade, regenerate with
 * {@code -Dfinora.golden.regenerate=true} and READ THE DIFF -- a column x-coordinate moving by
 * 0.01pt is noise, a run splitting in two is a bug in waiting, because PdfTableLocator buckets
 * by nearest x and joins runs with a single space.
 */
class PdfTextExtractorSnapshotTest {

    private static final Path FIXTURE =
            Path.of("src", "test", "resources", "pdf", "separate_debit_credit_balance_sample.pdf");

    private static final Path GOLDEN =
            Path.of("src", "test", "resources", "golden", "extractor-separate-debit-credit-balance.golden.txt");

    @Test
    void theCommittedPdfExtractsToItsCommittedRuns() throws IOException {
        List<PositionedText> runs = new PdfTextExtractor().extract(Files.readAllBytes(FIXTURE));
        String actual = render(runs, PdfTraceRedactor.redact(runs));

        if (Boolean.getBoolean("finora.golden.regenerate") || !Files.exists(GOLDEN)) {
            Files.createDirectories(GOLDEN.getParent());
            Files.writeString(GOLDEN, actual, StandardCharsets.UTF_8);
            return;
        }

        // Git on Windows checks committed text out with CRLF; without this every line would
        // "differ" for reasons that have nothing to do with extraction.
        String expected = Files.readString(GOLDEN, StandardCharsets.UTF_8).replace("\r\n", "\n");

        assertThat(actual)
                .as("""
                    PdfTextExtractor's output changed for a PDF whose bytes did not.

                    The same file now extracts different text runs, positions or widths. If you
                    upgraded PDFBox, this is the question that upgrade has to answer: read the
                    difference before regenerating. A shifted x-coordinate changes which column
                    PdfTableLocator buckets an amount into, which is the difference between a
                    debit and a credit.""")
                .isEqualTo(expected);
    }

    /**
     * One line per run: every field PositionedText carries, since each one feeds the locator.
     *
     * <p>Coordinates come from the RAW runs and only the text is taken from the redacted ones.
     * {@link PdfTraceRedactor#redact} builds its output through PositionedText's 4-arg constructor,
     * which defaults width to 0 -- so redacting first and rendering second would silently zero the
     * one field that exists to separate two adjacent right-aligned amount columns, and this
     * snapshot would go blind to exactly the regression it is most worth catching (PDFBOX-5920,
     * fixed in 3.0.4, was a wrong space width in PDType0Font). A width is a measurement in points;
     * it identifies nobody, so keeping it costs no privacy. The two lists are the same size and
     * order by construction.
     */
    private String render(List<PositionedText> raw, List<PositionedText> redacted) {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < raw.size(); i++) {
            PositionedText r = raw.get(i);
            sb.append(r.pageIndex()).append('\t')
                    .append(String.format(Locale.ROOT, "%.4f", r.x())).append('\t')
                    .append(String.format(Locale.ROOT, "%.4f", r.y())).append('\t')
                    .append(String.format(Locale.ROOT, "%.4f", r.width())).append('\t')
                    .append(redacted.get(i).text().replace("\t", "\\t").replace("\n", "\\n"))
                    .append('\n');
        }
        return sb.toString();
    }
}
