#!/usr/bin/env python3
"""
Repository Guardian report -- joins the rule manifest against surefire results.

    mvn -f backend/pom.xml test
    python3 scripts/guardian-report.py

The manifest (backend/target/guardian-rules.json) is generated by GuardianRegistryTest from the
@GuardianRule annotations, so this script never carries its own copy of the rule list and cannot
disagree with the code about which rules exist.

Reports a PASS RATE over the enumerated rules, deliberately not a "repository health" percentage.
The distinction is the one repository-guardian.md 4.3 argues for and it is not pedantry: a health
score implies a denominator covering everything that could be wrong, which nobody has agreed and
which no rule set approximates. A pass rate has an honest denominator -- the rules that exist --
and it makes adding a rule that finds real problems read as new information rather than as the
repository getting worse.

Exit codes: 0 all rules pass, 1 one or more failed, 2 the report could not be produced.
"""
import json
import os
import sys
import xml.etree.ElementTree as ET
from collections import defaultdict

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MANIFEST = os.path.join(REPO, "backend", "target", "guardian-rules.json")
SUREFIRE = os.path.join(REPO, "backend", "target", "surefire-reports")

GREEN, RED, YELLOW, DIM, BOLD, RESET = (
    "\033[32m", "\033[31m", "\033[33m", "\033[2m", "\033[1m", "\033[0m")
if os.environ.get("NO_COLOR") or not sys.stdout.isatty():
    GREEN = RED = YELLOW = DIM = BOLD = RESET = ""


def die(message, hint=""):
    print(f"{RED}Repository Guardian: {message}{RESET}", file=sys.stderr)
    if hint:
        print(f"  {hint}", file=sys.stderr)
    sys.exit(2)


def load_manifest():
    if not os.path.exists(MANIFEST):
        die("no rule manifest found.",
            "Run the backend suite first: mvn -f backend/pom.xml test")
    with open(MANIFEST, encoding="utf-8") as fh:
        return json.load(fh)


def load_results():
    """Map of 'fully.qualified.Class#method' -> 'PASS' | 'FAIL' | 'SKIP'."""
    if not os.path.isdir(SUREFIRE):
        die("no surefire reports found.",
            "Run the backend suite first: mvn -f backend/pom.xml test")
    results = {}
    for fn in os.listdir(SUREFIRE):
        if not (fn.startswith("TEST-") and fn.endswith(".xml")):
            continue
        try:
            root = ET.parse(os.path.join(SUREFIRE, fn)).getroot()
        except ET.ParseError:
            continue
        for case in root.iter("testcase"):
            cls = case.get("classname")
            name = (case.get("name") or "").split("(")[0]
            if not cls or not name:
                continue
            status = "PASS"
            if case.find("failure") is not None or case.find("error") is not None:
                status = "FAIL"
            elif case.find("skipped") is not None:
                status = "SKIP"
            results[f"{cls}#{name}"] = status
    return results


def main():
    rules = load_manifest()
    results = load_results()

    by_category = defaultdict(list)
    for rule in rules:
        key = f"{rule['testClass']}#{rule['testMethod']}"
        rule["status"] = results.get(key, "NOT RUN")
        by_category[rule["category"]].append(rule)

    passed = sum(1 for r in rules if r["status"] == "PASS")
    failed = sum(1 for r in rules if r["status"] == "FAIL")
    not_run = sum(1 for r in rules if r["status"] not in ("PASS", "FAIL"))
    total = len(rules)

    print()
    print(f"{BOLD}Repository Guardian{RESET}")
    print(f"{DIM}backend -- ArchUnit structural and behavioural rules{RESET}")
    print()

    width = max(len(c) for c in by_category) if by_category else 10
    for category in sorted(by_category):
        entries = sorted(by_category[category], key=lambda r: r["id"])
        cat_failed = [r for r in entries if r["status"] == "FAIL"]
        mark = f"{RED}FAIL{RESET}" if cat_failed else f"{GREEN}PASS{RESET}"
        print(f"  {mark}  {category.ljust(width)}  "
              f"{len(entries) - len(cat_failed)}/{len(entries)}")
        for rule in entries:
            if rule["status"] == "PASS":
                continue
            colour = RED if rule["status"] == "FAIL" else YELLOW
            print(f"        {colour}{rule['id']} {rule['status']}{RESET}  {rule['intent']}")
            if rule["status"] == "FAIL":
                print(f"          {DIM}{rule['testClass'].rsplit('.', 1)[-1]}"
                      f"#{rule['testMethod']}{RESET}")

    print()
    rate = (passed / total * 100) if total else 0.0
    summary_colour = GREEN if failed == 0 and not_run == 0 else RED
    print(f"  {BOLD}{total} rules{RESET}   "
          f"{GREEN}{passed} pass{RESET}   "
          f"{RED if failed else DIM}{failed} fail{RESET}   "
          f"{YELLOW if not_run else DIM}{not_run} not run{RESET}")
    print(f"  {summary_colour}Rule pass rate: {rate:.0f}%  ({passed}/{total}){RESET}")

    verified = sum(1 for r in rules if r["verification"] == "SELF_TEST")
    excepted = sum(1 for r in rules if r["exceptions"])
    print(f"  {DIM}{verified}/{total} rules carry self-tests   "
          f"{excepted} carry accepted exceptions{RESET}")
    print()

    if failed:
        print(f"  {DIM}Rule detail: docs/architecture/"
              f"repository-guardian-rules.md{RESET}")
        print()
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
